/**
 * Generates .content/generated.ts from the JSON in /content.
 * Validates required fields so a typo in a content file fails at build time.
 * Run automatically before `next build` and `next dev` (see package.json).
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const read = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, "content", f), "utf8"));

const errors = [];
const fail = (msg) => errors.push(msg);
const isStr = (v) => typeof v === "string" && v.length > 0;

// ---- properties.json ----
const properties = read("properties.json").properties;
if (!Array.isArray(properties) || properties.length !== 2) {
  fail("properties.json: expected exactly 2 properties (puri, bhubaneswar)");
}
for (const p of properties) {
  if (!isStr(p.key)) fail(`properties.json: property missing key`);
  if (!isStr(p.name)) fail(`properties.json[${p.key}]: missing name`);
  if (!isStr(p.address)) fail(`properties.json[${p.key}]: missing address`);
  if (!/^91\d{10}$/.test(p.phonePrimary || "")) {
    fail(`properties.json[${p.key}]: phonePrimary must be 91XXXXXXXXXX format`);
  }
  if (!p.distanceChips || !Array.isArray(p.distanceChips)) {
    fail(`properties.json[${p.key}]: missing distanceChips array`);
  }
}

// ---- rooms.json ----
const rooms = read("rooms.json").rooms;
for (const r of rooms) {
  if (!isStr(r.id)) fail(`rooms.json: room missing id`);
  if (!isStr(r.name)) fail(`rooms.json[${r.id}]: missing name`);
  if (typeof r.maxGuests !== "number") fail(`rooms.json[${r.id}]: maxGuests must be a number`);
  if (!properties.some((p) => p.key === r.property)) {
    fail(`rooms.json[${r.id}]: unknown property "${r.property}"`);
  }
}

// ---- media.manifest.json ----
const media = read("media.manifest.json").items;
const mediaIds = new Set();
for (const m of media) {
  if (!isStr(m.id)) fail(`media.manifest.json: item missing id`);
  else if (mediaIds.has(m.id)) fail(`media.manifest.json: duplicate id "${m.id}"`);
  if (m.id) mediaIds.add(m.id);
  if (m.type === "image" && !isStr(m.src)) fail(`media.manifest.json[${m.id}]: image missing src`);
  if (m.type === "video" && m.src && !isStr(m.poster)) {
    fail(`media.manifest.json[${m.id}]: video with src must have a poster`);
  }
}

// ---- referential integrity ----
for (const r of rooms) {
  if (r.imageId && !mediaIds.has(r.imageId)) {
    fail(`rooms.json[${r.id}]: imageId "${r.imageId}" not found in media manifest`);
  }
}
for (const p of properties) {
  if (p.heroImageId && !mediaIds.has(p.heroImageId)) {
    fail(`properties.json[${p.key}]: heroImageId "${p.heroImageId}" not in media manifest`);
  }
  for (const n of p.nearby || []) {
    if (n.imageId && !mediaIds.has(n.imageId)) {
      fail(`properties.json[${p.key}]: nearby "${n.name}" imageId "${n.imageId}" not in manifest`);
    }
  }
}

// ---- faq.json / policies.json / explore.json ----
const faqs = read("faq.json").faqs;
for (let i = 0; i < faqs.length; i++) {
  if (!isStr(faqs[i].q)) fail(`faq.json[${i}]: missing q`);
  if (!isStr(faqs[i].a)) fail(`faq.json[${i}]: missing a`);
}
const policies = read("policies.json").policies;
for (let i = 0; i < policies.length; i++) {
  if (!isStr(policies[i].label)) fail(`policies.json[${i}]: missing label`);
  if (!isStr(policies[i].text)) fail(`policies.json[${i}]: missing text`);
}
const explore = read("explore.json");
for (const city of ["puri", "bhubaneswar"]) {
  if (!explore[city] || !Array.isArray(explore[city].top5)) {
    fail(`explore.json: missing ${city}.top5`);
  }
}

if (errors.length) {
  console.error("\n✗ Content validation failed:");
  for (const e of errors) console.error("  - " + e);
  process.exit(1);
}

const out = `// AUTO-GENERATED by scripts/generate-content.js — do not edit.
// Edit the JSON files in /content; this file is rebuilt on build/dev.
import propertiesJson from "@/content/properties.json";
import roomsJson from "@/content/rooms.json";
import reviewsJson from "@/content/reviews.json";
import mediaJson from "@/content/media.manifest.json";
import faqsJson from "@/content/faq.json";
import policiesJson from "@/content/policies.json";
import exploreJson from "@/content/explore.json";
import offersJson from "@/content/offers.json";
import siteExtrasJson from "@/content/site-extras.json";

export const propertiesData = propertiesJson.properties;
export const roomsData = roomsJson.rooms;
export const reviewsData = reviewsJson.reviews;
export const mediaData = mediaJson.items;
export const faqData = faqsJson.faqs;
export const policiesData = policiesJson.policies;
export const policiesPrivacyNote = policiesJson.privacyNote;
export const exploreData = exploreJson;
export const offersData = offersJson;
export const siteExtrasData = siteExtrasJson;
`;

fs.writeFileSync(path.join(ROOT, ".content", "generated.ts"), out, "utf8");
console.log("✓ Content validated and .content/generated.ts written.");
