// AUTO-GENERATED by scripts/generate-content.js — do not edit.
// Edit the JSON files in /content; this file is rebuilt on build/dev.
import propertiesJson from "@/content/properties.json";
import roomsJson from "@/content/rooms.json";
import reviewsJson from "@/content/reviews.json";
import mediaJson from "@/content/media.manifest.json";
import faqsJson from "@/content/faq.json";
import policiesJson from "@/content/policies.json";
import exploreJson from "@/content/explore.json";
import offersJson from "@/content/offers.json";
import siteExtrasJson from "@/content/site-extras.json";

export const propertiesData = propertiesJson.properties;
export const roomsData = roomsJson.rooms;
export const reviewsData = reviewsJson.reviews;
export const mediaData = mediaJson.items;
export const faqData = faqsJson.faqs;
export const policiesData = policiesJson.policies;
export const policiesPrivacyNote = policiesJson.privacyNote;
export const exploreData = exploreJson;
export const offersData = offersJson;
export const siteExtrasData = siteExtrasJson;
